### ISSUE TITLE
Use with CodeSandBox

### ISSUE THREAD

**Issue by writingdeveloper** [esausilva/example-create-react-app-express#9]
I currently developing based on this repository. I wonder how to use this in Codesandbox.

When I use it in codesandbox it shows lots of errors.

It seems the error from scripts but I don't know where should I fix it.

Can you check it please?

https://codesandbox.io/s/github/esausilva/example-create-react-app-express

**Comment by esausilva** [comment]
Hi, I don't think it is possible to run this project (as-is) in CodeSandbox because the project is actually two apps, the Node app and the React app.

You could run the React app by itself in CodeSandbox (not directly from the repo) and then deploy the Node app to a cloud function somewhere else, then replace the API calls to point to the cloud function.
